ITEMS: dict[str, tuple[str, str, str, int, int, str]] = {
    "0100": ("Hero item", "Hero item", "", -1, -1, ""),
    "0200": ("Hero item", "Hero item", "", -1, -1, ""),
    "0300": ("Hero item", "Hero item", "", -1, -1, ""),
    "0400": ("Hero item", "Hero item", "", -1, -1, ""),
    "0500": ("Hero item", "Hero item", "", -1, -1, ""),
    "0600": ("Hero item", "Hero item", "", -1, -1, ""),
    "0700": ("Hero item", "Hero item", "", -1, -1, ""),
    "0800": ("Hero item", "Hero item", "", -1, -1, ""),
    "0900": ("Hero item", "Hero item", "", -1, -1, ""),
    "0a00": ("Hero item", "Hero item", "", -1, -1, ""),
    "0b00": ("Hero item", "Hero item", "", -1, -1, ""),
    "0c00": ("Hero item", "Hero item", "", -1, -1, ""),
    "0d00": ("Hero item", "Hero item", "", -1, -1, ""),
    "0e00": ("Hero item", "Hero item", "", -1, -1, ""),
    "0f00": ("Hero item", "Hero item", "", -1, -1, ""),
    "1000": ("Hero item", "Hero item", "", -1, -1, ""),
    "1100": ("Hero item", "Hero item", "", -1, -1, ""),
    "1200": ("Hero item", "Hero item", "", -1, -1, ""),
    "1900": ("Hero item", "Hero item", "", -1, -1, ""),
    "1a00": ("Hero item", "Hero item", "", -1, -1, ""),
    "1b00": ("Hero item", "Hero item", "", -1, -1, ""),
    "1c00": ("Hero item", "Hero item", "", -1, -1, ""),
    "1d00": ("Hero item", "Hero item", "", -1, -1, ""),
    "1e00": ("Hero item", "Hero item", "", -1, -1, ""),
    "c900": ("Hero item", "Hero item", "", -1, -1, ""),
    "ca00": ("Hero item", "Hero item", "", -1, -1, ""),
    "cb00": ("Hero item", "Hero item", "", -1, -1, ""),
    "cc00": ("Hero item", "Hero item", "", -1, -1, ""),
    "cd00": ("Hero item", "Hero item", "", -1, -1, ""),
    "ce00": ("Hero item", "Hero item", "", -1, -1, ""),
    "cf00": ("Hero item", "Hero item", "", -1, -1, ""),
    "d000": ("Hero item", "Hero item", "", -1, -1, ""),
    "d100": ("Hero item", "Hero item", "", -1, -1, ""),
    "d200": ("Hero item", "Hero item", "", -1, -1, ""),
    "d300": ("Hero item", "Hero item", "", -1, -1, ""),
    "d400": ("Hero item", "Hero item", "", -1, -1, ""),
    "d500": ("Hero item", "Hero item", "", -1, -1, ""),
    "d600": ("Hero item", "Hero item", "", -1, -1, ""),
    "db00": ("Hero item", "Hero item", "", -1, -1, ""),
    "dc00": ("Hero item", "Hero item", "", -1, -1, ""),
    "f501": ("Hero item", "Hero item", "", -1, -1, ""),
    "f601": ("Hero item", "Hero item", "", -1, -1, ""),
    "f701": ("Hero item", "Hero item", "", -1, -1, ""),
    "f801": ("Hero item", "Hero item", "", -1, -1, ""),
    "f901": ("Hero item", "Hero item", "", -1, -1, ""),
    "fa01": ("Hero item", "Hero item", "", -1, -1, ""),
    "fb01": ("Hero item", "Hero item", "", -1, -1, ""),
    "fc01": ("Hero item", "Hero item", "", -1, -1, ""),
    "fd01": ("Hero item", "Hero item", "", -1, -1, ""),
    "fe01": ("Hero item", "Hero item", "", -1, -1, ""),
    "ff01": ("Hero item", "Hero item", "", -1, -1, ""),
    "0002": ("Hero item", "Hero item", "", -1, -1, ""),
    "0102": ("Hero item", "Hero item", "", -1, -1, ""),
    "0202": ("Hero item", "Hero item", "", -1, -1, ""),
    "0302": ("Hero item", "Hero item", "", -1, -1, ""),
    "0602": ("Hero item", "Hero item", "", -1, -1, ""),
    "0802": ("Hero item", "Hero item", "", -1, -1, ""),
    "0b02": ("Hero item", "Hero item", "", -1, -1, ""),
    "0d02": ("Hero item", "Hero item", "", -1, -1, ""),
    "1102": ("Hero item", "Hero item", "", -1, -1, ""),
    #
    "e903": ["Withdraw Squad", "Withdraw Squad", "", -1, -1, ""],
    "eb03": ["Random Relocator", "Random Relocator", "", -1, -1, ""],
    "ec03": ["Relocator", "Relocator", "", -1, -1, ""],
    "f103": ["30,000 Food", "Resources", "", -1, -1, ""],
    "f203": ["10,000 Stones", "Resources", "", -1, -1, ""],
    "f303": ["10,000 Timber", "Resources", "", -1, -1, ""],
    "f403": ["10,000 Ore", "Resources", "", -1, -1, ""],
    "f503": ["3,000 Gold", "Gold", "", -1, -1, ""],
    "f603": ["150,000 Food", "Resources", "", -1, -1, ""],
    "f703": ["50,000 Stones", "Resources", "", -1, -1, ""],
    "f803": ["50,000 Timber", "Resources", "", -1, -1, ""],
    "f903": ["50,000 Ore", "Resources", "", -1, -1, ""],
    "fa03": ["15,000 Gold", "Gold", "", -1, -1, ""],
    "fb03": ["500,000 Food", "Resources", "", -1, -1, ""],
    "fc03": ["150,000 Stones", "Resources", "", -1, -1, ""],
    "fd03": ["150,000 Timber", "Resources", "", -1, -1, ""],
    "fe03": ["150,000 Ore", "Resources", "", -1, -1, ""],
    "ff03": ["50,000 Gold", "Gold", "", -1, -1, ""],
    "0004": ["2,000,000 Food", "Resources", "", -1, -1, ""],
    "0104": ["500,000 Stones", "Resources", "", -1, -1, ""],
    "0204": ["500,000 Timber", "Resources", "", -1, -1, ""],
    "0304": ["500,000 Ore", "Resources", "", -1, -1, ""],
    "0404": ["200,000 Gold", "Gold", "", -1, -1, ""],
    # "0504": ["", "", "", -1, -1, ""],
    # "0604": ["", "", "", -1, -1, ""],
    "0704": ["Build Boost(10%)", "Turf Boost", "", -1, -1, ""],
    # "0804": ["", "", "", -1, -1, ""],
    # "0904": ["", "", "", -1, -1, ""],
    # "0a04": ["", "", "", -1, -1, ""],
    # "0b04": ["", "", "", -1, -1, ""],
    # "0c04": ["", "", "", -1, -1, ""],
    "0d04": ["Gather Boost(50%)", "Turf Boost", "", -1, -1, ""],  # 1day
    # "0e04": ["", "", "", -1, -1, ""],
    #
    "0f04": ["Winged Boots I", "Winged Boots", "", -1, -1, ""],
    "1004": ["Speed Up(15m)", "Speed Up", "", -1, -1, ""],
    "1104": ["Speed Up(30m)", "Speed Up", "", -1, -1, ""],
    "1204": ["Speed Up(60m)", "Speed Up", "", -1, -1, ""],
    "1304": ["100 VIP Points", "VIP Points", "", -1, -1, ""],
    "1404": ["500 VIP Points", "VIP Points", "", -1, -1, ""],
    "1504": ["1000 VIP Points", "VIP Points", "", -1, -1, ""],
    "1604": ["5000 VIP Points", "VIP Points", "", -1, -1, ""],
    #
    "1b04": ["Shield(8h)", "Shield", "", -1, -1, ""],
    "1c04": ["Shield(24h)", "Shield", "", -1, -1, ""],
    "1d04": ["Shield(3days)", "Shield", "", -1, -1, ""],
    "1e04": ["Anti-Scout(24h)", "Anti-Scout", "", -1, -1, ""],
    "1f04": ["Anti-Scout(3days)", "Anti-Scout", "", -1, -1, ""],
    "2004": ["Anti-Scout(7days)", "Anti-Scout", "", -1, -1, ""],
    # "2104": ["", "", "", -1, -1, ""],
    # "2204": ["", "", "", -1, -1, ""],
    # "2304": ["", "", "", -1, -1, ""],
    # "2404": ["", "", "", -1, -1, ""],
    # "2504": ["", "", "", -1, -1, ""],
    # "2604": ["", "", "", -1, -1, ""],
    # "2704": ["", "", "", -1, -1, ""],
    # "2804": ["", "", "", -1, -1, ""],
    "2904": ["Food Boost (25%)", "Turf Boost", "", -1, -1, ""],
    "2a04": ["Stone Boost (25%)", "Turf Boost", "", -1, -1, ""],
    "2b04": ["Timber Boost (25%)", "Turf Boost", "", -1, -1, ""],
    "2C04": ["Ore Boost (25%)", "Turf Boost", "", -1, -1, ""],
    "2d04": ["Gold Boost (25%)", "Turf Boost", "", -1, -1, ""],
    "3904": ["Speed Up(3h)", "Speed Up", "", -1, -1, ""],
    "3a04": ["Speed Up(8h)", "Speed Up", "", -1, -1, ""],
    "3b04": ["Speed Up(15h)", "Speed Up", "", -1, -1, ""],
    "3c04": ["Speed Up(24h)", "Speed Up", "", -1, -1, ""],
    "3d04": ["Speed Up(3 days)", "Speed Up", "", -1, -1, ""],
    # "3e04": ["", "", "", -1, -1, ""],
    # "3f04": ["", "", "", -1, -1, ""],
    "4004": ["War Tome", "War Tome", "", -1, -1, ""],
    "4104": ["Crystal Pickaxe", "Crystal Pickaxe", "", -1, -1, ""],
    "4204": ["Steel Cuffs", "Steel Cuffs", "", -1, -1, ""],
    "4304": ["Soul Crystal", "Soul Crystal", "", -1, -1, ""],
    # "4404": ["", "", "", -1, -1, ""],
    "4504": ["6,000,000 Food", "Resources", "", -1, -1, ""],
    "4604": ["1,500,000 Stones", "Resources", "", -1, -1, ""],
    "4704": ["1,500,000 Timber", "Resources", "", -1, -1, ""],
    "4804": ["1,500,000 Ore", "Resources", "", -1, -1, ""],
    "4904": ["600,000 Gold", "Gold", "", -1, -1, ""],
    "5804": ["Quest Scroll (Admin)", "Quest Scroll", "", -1, -1, ""],
    "5904": ["Quest Scroll (Guild)", "Quest Scroll", "", -1, -1, ""],
    "5b04": ["Braveheart", "Braveheart", "", -1, -1, ""],
    "5e04": ["Bookmark Space", "Bookmark Space", "", -1, -1, ""],
    "6104": ["Winged Boots II", "Winged Boots", "", -1, -1, ""],
    "6304": ["1,000 Gems", "Gems", "", -1, -1, ""],
    "6604": ["Gather Boost(50%)", "Turf Boost", "", -1, -1, ""],  # 7day
    "7804": ["Speed Up(5m)", "Speed Up", "", -1, -1, ""],
    "7a04": ["Shield(4h)", "Shield", "", -1, -1, ""],
    "7b04": ["Anti-Scout(4h)", "Anti-Scout", "", -1, -1, ""],
    "7c04": ["Speed Up(3m)", "Speed Up", "", -1, -1, ""],
    "7d04": ["Speed Up(10m)", "Speed Up", "", -1, -1, ""],
    "8404": ["Anti-Scout(8h)", "Anti-Scout", "", -1, -1, ""],
    "8604": ["False Info(2x)", "False Info", "", -1, -1, ""],
    "8a04": ["1,000 Energy", "Energy", "", -1, -1, ""],
    "8b04": ["2,000 Energy", "Energy", "", -1, -1, ""],
    "8c04": ["5,000 Energy", "Energy", "", -1, -1, ""],
    "8d04": ["10,000 Energy", "Energy", "", -1, -1, ""],
    "8e04": ["20,000 Energy", "Energy", "", -1, -1, ""],
    "8f04": ["50,000 Energy", "Energy", "", -1, -1, ""],
    # "9004": ["50,000 Energy", "Energy", "", -1, -1, ""],
    "9104": ["50 Gems", "Gems", "", -1, -1, ""],
    "9204": ["5,000 Food", "Resources", "", -1, -1, ""],
    "9304": ["3,000 Stones", "Resources", "", -1, -1, ""],
    "9404": ["3,000 Timber", "Resources", "", -1, -1, ""],
    "9504": ["3,000 Ore", "Resources", "", -1, -1, ""],
    "9604": ["1,500 Gold", "Gold", "", -1, -1, ""],
    "9a04": ["500 Gems", "Gems", "", -1, -1, ""],
    "c104": ["1,000 Guild Coin", "Guild Coin", "", -1, -1, ""],
    "c204": ["2,000 Guild Coin", "Guild Coin", "", -1, -1, ""],
    "c304": ["3,000 Guild Coin", "Guild Coin", "", -1, -1, ""],
    "c404": ["5,000 Guild Coin", "Guild Coin", "", -1, -1, ""],
    "c504": ["10,000 Guild Coin", "Guild Coin", "", -1, -1, ""],
    "c604": ["20,000 Guild Coin", "Guild Coin", "", -1, -1, ""],
    "c704": ["30,000 Guild Coin", "Guild Coin", "", -1, -1, ""],
    #
    "c904": ["100 Gems", "Gems", "", -1, -1, ""],
    "ca04": ["200 Gems", "Gems", "", -1, -1, ""],
    "cb04": ["300 Gems", "Gems", "", -1, -1, ""],
    "cc04": ["400 Gems", "Gems", "", -1, -1, ""],
    "cd04": ["600 Gems", "Gems", "", -1, -1, ""],
    "ce04": ["800 Gems", "Gems", "", -1, -1, ""],
    "d604": ["50,000 Guild Coin", "Guild Coin", "", -1, -1, ""],
    # "d904": ["", "", "", -1, -1, ""],  # popped from Amethyst Box
    "e904": ["Speed Up Research(5m)", "Speed Up Research", "", -1, -1, ""],
    "ea04": ["Speed Up Research(10m)", "Speed Up Research", "", -1, -1, ""],
    "eb04": ["Speed Up Research(15m)", "Speed Up Research", "", -1, -1, ""],
    "ec04": ["Speed Up Research(30m)", "Speed Up Research", "", -1, -1, ""],
    "ed04": ["Speed Up Research(60m)", "Speed Up Research", "", -1, -1, ""],
    "ee04": ["Speed Up Research(3h)", "Speed Up Research", "", -1, -1, ""],
    "ef04": ["Speed Up Research(8h)", "Speed Up Research", "", -1, -1, ""],
    "f004": ["Speed Up Research(15h)", "Speed Up Research", "", -1, -1, ""],
    "f104": ["Speed Up Research(24h)", "Speed Up Research", "", -1, -1, ""],
    #
    "fc04": ["Speed Up Wall Repair(15m)", "Speed Up Wall Repair",
             "", -1, -1, ""],
    "fd04": ["Speed Up Wall Repair(60m)", "Speed Up Wall Repair",
             "", -1, -1, ""],
    #
    "0205": ["Speed Up Healing(15m)", "Speed Up Healing", "", -1, -1, ""],
    "0305": ["Speed Up Healing(60m)", "Speed Up Healing", "", -1, -1, ""],
    #
    "1a05": ["100 Holly Stars", "Holly Stars", "", -1, -1, ""],
    "2005": ["500 Holly Stars", "Holly Stars", "", -1, -1, ""],
    "2705": ["Speed Up Training(30m)", "Speed Up Training", "", -1, -1, ""],
    "2805": ["Speed Up Training(60m)", "Speed Up Training", "", -1, -1, ""],
    #
    "2e05": ["Star Scroll", "Star Scroll", "", -1, -1, ""],
    # -------------------------------------------------------------------------
    # bonus, chest, loot
    "dc05": ["[Uncommon]Steampath Bonus", "Bonus", "", 2, 1, ""],
    "d307": ["[Rare]Material Chest", "Chest", "", 3, 4, ""],
    "d407": ["[Epic]Material Chest", "Chest", "", 4, 4, ""],
    "d507": ["[Legendary]Material Chest", "Chest", "", 5, 4, ""],
    "da07": ["Cabinet Expander", "Cabinet Expander", "", -1, -1, ""],
    "e007": ["Silver Box", "Guild Box", "", 0, 2, ""],
    "e107": ["Emerald Box", "Guild Box", "", 0, 2, ""],
    "e207": ["Sapphire Box", "Guild Box", "", 0, 2, ""],
    "e307": ["Amethyst Box", "Guild Box", "", 0, 2, ""],
    "e407": ["Golden Box", "Guild Box", "", 0, 2, ""],
    # "e507": ["", "", "", -1, -1, ""],
    # "e607": ["", "", "", -1, -1, ""],
    # "e707": ["", "", "", -1, -1, ""],
    # "e807": ["", "", "", -1, -1, ""],
    # "e907": ["", "", "", -1, -1, ""],
    # "ea07": ["", "", "", -1, -1, ""],
    # "eb07": ["", "", "", -1, -1, ""],
    # "ec07": ["", "", "", -1, -1, ""],
    "ed07": ["[Rare]Jewel Chest", "Chest", "", -1, -1, ""],
    "ee07": ["[Epic]Jewel Chest", "Chest", "", -1, -1, ""],
    "ef07": ["[Legendary]Jewel Chest", "Chest", "", -1, -1, ""],
    "f007": ["[Common]Hero Chest", "Chest", "", 1, 4, ""],
    "f107": ["[Uncommon]Hero Chest", "Chest", "", 2, 4, ""],
    "f207": ["[Rare]Hero Chest", "Chest", "", 3, 4, ""],
    "f307": ["[Epic]Hero Chest", "Chest", "", 4, 4, ""],
    "f407": ["[Legendary]Hero Chest", "Chest", "", 5, 4, ""],
    "f507": ["[Uncommon]Guild War Chest", "Event Chest", "", 2, 3, ""],
    "f607": ["[Rare]Guild War Chest", "Event Chest", "", 3, 3, ""],
    "f707": ["[Epic]Guild War Chest", "Event Chest", "", 4, 3, ""],
    "f807": ["[Uncommon]Guild Cup Chest", "Event Chest", "", 2, 3, ""],
    "f907": ["[Rare]Guild Cup Chest", "Event Chest", "", 3, 3, ""],
    "fa07": ["[Epic]Guild Cup Chest", "Event Chest", "", 4, 3, ""],
    # -------------------------
    # "a609": ["[Uncommon]Jade Wyrm Bonus", "Bonus", "", 2, 1, ""],
    "cb09": ["[Common]Frostwing Loot", "Loot", "", 1, 0, "Frostwing"],
    "cc09": ["[Uncommon]Frostwing Loot", "Loot", "", 2, 0, "Frostwing"],
    "cd09": ["[Rare]Frostwing Loot", "Loot", "", 3, 0, "Frostwing"],
    "ce09": ["[Epic]Frostwing Loot", "Loot", "", 4, 0, "Frostwing"],
    "cf09": ["[Legendary]Frostwing Loot", "Loot", "", 5, 0, "Frostwing"],
    # -------------------------
    "d009": ["[Common]White Bonus", "Bonus", "", 1, 1, ""],
    "d109": ["[Uncommon]Green Bonus", "Bonus", "", 2, 1, ""],
    "d209": ["[Rare]Blue Bonus", "Bonus", "", 3, 1, ""],
    "d309": ["[Epic]Purple Bonus", "Bonus", "", 4, 1, ""],
    "d409": ["[Legendary]Gold Bonus", "Bonus", "", 5, 1, ""],

    # -------------------------------------------------------------------------
    # chest, bonus, loot for
    # - Snow Beast
    # - Gryphon
    "d509": ["[Legendary]Snow Beast Chest", "Chest", "", 5, 4, ""],
    "d609": ["[Legendary]Gryphon Chest", "Chest", "", 5, 4, ""],
    "d709": ["[Uncommon]Snow Beast Bonus", "Bonus", "", 2, 1, ""],
    # "d809": ["[Rare]Snow Beast Bonus", "Bonus", "", 3, 1, ""],
    # "d909": ["[Epic]Snow Beast Bonus", "Bonus", "", 4, 1, ""],
    # "da09": ["[Legendary]Snow Beast Bonus", "Bonus", "", 5, 1, ""],
    # "db09": ["[Uncommon]Gryphon Bonus", "Bonus", "", 2, 1, ""],
    # "dc09": ["[Rare]Gryphon Bonus", "Bonus", "", 3, 1, ""],
    # "dd09": ["[Epic]Gryphon Bonus", "Bonus", "", 4, 1, ""],
    # "de09": ["[Legendary]Gryphon Bonus", "Bonus", "", 5, 1, ""],
    "df09": ["[Common]Snow Beast Loot", "Loot", "", 1, 0, "Snow Beast"],
    "e009": ["[Uncommon]Snow Beast Loot", "Loot", "", 2, 0, "Snow Beast"],
    "e109": ["[Rare]Snow Beast Loot", "Loot", "", 3, 0, "Snow Beast"],
    "e209": ["[Epic]Snow Beast Loot", "Loot", "", 4, 0, "Snow Beast"],
    "e309": ["[Legendary]Snow Beast Loot", "Loot", "", 5, 0, "Snow Beast"],
    "e409": ["[Common]Gryphon Loot", "Loot", "", 1, 0, "Gryphon"],
    "e509": ["[Uncommon]Gryphon Loot", "Loot", "", 2, 0, "Gryphon"],
    "e609": ["[Rare]Gryphon Loot", "Loot", "", 3, 0, "Gryphon"],
    "e709": ["[Epic]Gryphon Loot", "Loot", "", 4, 0, "Gryphon"],
    "e809": ["[Legendary]Gryphon Loot", "Loot", "", 5, 0, "Gryphon"],
    # -------------------------------------------------------------------------

    # "e909": ["", "", "", -1, -1, ""],
    # "ea09": ["", "", "", -1, -1, ""],
    # "eb09": ["", "", "", -1, -1, ""],
    # "ec09": ["", "", "", -1, -1, ""],
    # "ed09": ["", "", "", -1, -1, ""],

    # -------------------------------------------------------------------------
    # chest, bonus, loot for
    # - Champion
    # - Jade Wyrm
    # - Terrorthorn
    # - Gargantua
    # - Mega Maggot
    # +alpha
    "ee09": ["[Legendary]Champion Chest", "Chest", "", 5, 4, ""],
    "ef09": ["[Legendary]Wyrm Chest", "Chest", "", 5, 4, ""],
    "f009": ["[Legendary]Terror Chest", "Chest", "", 5, 4, ""],
    "f109": ["[Legendary]Gargantuan Chest", "Chest", "", 5, 4, ""],
    "f209": ["[Legendary]Maggot Chest", "Chest", "", 5, 4, ""],
    # "f309": ["", "", "", -1, -1, ""],
    # "f409": ["", "", "", -1, -1, ""],
    # "f509": ["", "", "", -1, -1, ""],
    "f609": ["[Legendary]Champion Bonus", "Bonus", "", 5, 1, ""],
    # "f709": ["[Uncommon]Jade Wyrm Bonus", "Bonus", "", 2, 1, ""],
    # "f809": ["[Rare]Jade Wyrm Bonus", "Bonus", "", 3, 1, ""],
    # "f909": ["[Epic]Jade Wyrm Bonus", "Bonus", "", 4, 1, ""],
    # "fa09": ["[Legendary]Jade Wyrm Bonus", "Bonus", "", 5, 1, ""],
    "fb09": ["[Uncommon]Terrorthorn Bonus", "Bonus", "", 2, 1, ""],
    # "fc09": ["[Rare]Terrorthorn Bonus", "Bonus", "", 3, 1, ""],
    # "fd09": ["[Epic]Terrorthorn Bonus", "Bonus", "", 4, 1, ""],
    # "fe09": ["[Legendary]Terrorthorn Bonus", "Bonus", "", 5, 1, ""],
    "ff09": ["[Uncommon]Gargantua Bonus", "Bonus", "", 2, 1, ""],
    # "000a": ["[Rare]Gargantua Bonus", "Bonus", "", 3, 1, ""],
    # "010a": ["[Epic]Gargantua Bonus", "Bonus", "", 4, 1, ""],
    # "020a": ["[Legendary]Gargantua Bonus", "Bonus", "", 5, 1, ""],
    # "030a": ["[Uncommon]Mega Maggot Bonus", "Bonus", "", 2, 1, ""],
    # "040a": ["[Rare]Mega Maggot Bonus", "Bonus", "", 3, 1, ""],
    # "050a": ["[Epic]Mega Maggot Bonus", "Bonus", "", 4, 1, ""],
    # "060a": ["[Legendary]Mega Maggot Bonus", "Bonus", "", 5, 1, ""],
    "070a": ["[Common]Jade Wyrm Loot", "Loot", "", 1, 0, "Jade Wyrm"],
    "080a": ["[Uncommon]Jade Wyrm Loot", "Loot", "", 2, 0, "Jade Wyrm"],
    "090a": ["[Rare]Jade Wyrm Loot", "Loot", "", 3, 0, "Jade Wyrm"],
    "0a0a": ["[Epic]Jade Wyrm Loot", "Loot", "", 4, 0, "Jade Wyrm"],
    "0b0a": ["[Legendary]Jade Wyrm Loot", "Loot", "", 5, 0, "Jade Wyrm"],
    "0c0a": ["[Common]Terrorthorn Loot", "Loot", "", 1, 0, "Terrorthorn"],
    "0d0a": ["[Uncommon]Terrorthorn Loot", "Loot", "", 2, 0, "Terrorthorn"],
    "0e0a": ["[Rare]Terrorthorn Loot", "Loot", "", 3, 0, "Terrorthorn"],
    "0f0a": ["[Epic]Terrorthorn Loot", "Loot", "", 4, 0, "Terrorthorn"],
    "100a": ["[Legendary]Terrorthorn Loot", "Loot", "", 5, 0, "Terrorthorn"],
    "110a": ["[Common]Gargantua Loot", "Loot", "", 1, 0, "Gargantua"],
    "120a": ["[Uncommon]Gargantua Loot", "Loot", "", 2, 0, "Gargantua"],
    "130a": ["[Rare]Gargantua Loot", "Loot", "", 3, 0, "Gargantua"],
    "140a": ["[Epic]Gargantua Loot", "Loot", "", 4, 0, "Gargantua"],
    "150a": ["[Legendary]Gargantua Loot", "Loot", "", 5, 0, "Gargantua"],
    "160a": ["[Common]Mega Maggot Loot", "Loot", "", 1, 0, "Mega Maggot"],
    "170a": ["[Uncommon]Mega Maggot Loot", "Loot", "", 2, 0, "Mega Maggot"],
    "180a": ["[Rare]Mega Maggot Loot", "Loot", "", 3, 0, "Mega Maggot"],
    "190a": ["[Epic]Mega Maggot Loot", "Loot", "", 4, 0, "Mega Maggot"],
    "1a0a": ["[Legendary]Mega Maggot Loot", "Loot", "", 5, 0, "Mega Maggot"],
    # -------------------------------------------------------------------------

    # "1b0a": ["", "", "", -1, -1, ""],
    "1c0a": ["[Rare]Supply Bonus", "Bonus", "", 3, 1, ""],

    # -------------------------------------------------------------------------
    # chest, bonus, loot for
    # - Hell Drider
    # - Grim Reaper
    "1d0a": ["[Legendary]Hell Drider Chest", "Chest", "", 5, 4, ""],
    "1e0a": ["[Legendary]Grim Reaper Chest", "Chest", "", 5, 4, ""],
    "1f0a": ["[Uncommon]Hell Drider Bonus", "Bonus", "", 2, 1, ""],
    "200a": ["[Rare]Hell Drider Bonus", "Bonus", "", 3, 1, ""],
    "210a": ["[Epic]Hell Drider Bonus", "Bonus", "", 4, 1, ""],
    "220a": ["[Legendary]Hell Drider Bonus", "Bonus", "", 5, 1, ""],
    "230a": ["[Uncommon]Grim Reaper Bonus", "Bonus", "", 2, 1, ""],
    "240a": ["[Rare]Grim Reaper Bonus", "Bonus", "", 3, 1, ""],
    "250a": ["[Epic]Grim Reaper Bonus", "Bonus", "", 4, 1, ""],
    "260a": ["[Legendary]Grim Reaper Bonus", "Bonus", "", 5, 1, ""],
    "270a": ["[Common]Hell Drider Loot", "Loot", "", 1, 0, "Hell Drider"],
    "280a": ["[Uncommon]Hell Drider Loot", "Loot", "", 2, 0, "Hell Drider"],
    "290a": ["[Rare]Hell Drider Loot", "Loot", "", 3, 0, "Hell Drider"],
    "2a0a": ["[Epic]Hell Drider Loot", "Loot", "", 4, 0, "Hell Drider"],
    "2b0a": ["[Legendary]Hell Drider Loot", "Loot", "", 5, 0, "Hell Drider"],
    "2c0a": ["[Common]Grim Reaper Loot", "Loot", "", 1, 0, "Grim Reaper"],
    "2d0a": ["[Uncommon]Grim Reaper Loot", "Loot", "", 2, 0, "Grim Reaper"],
    "2e0a": ["[Rare]Grim Reaper Loot", "Loot", "", 3, 0, "Grim Reaper"],
    "2f0a": ["[Epic]Grim Reaper Loot", "Loot", "", 4, 0, "Grim Reaper"],
    "300a": ["[Legendary]Grim Reaper Loot", "Loot", "", 5, 0, "Grim Reaper"],

    # -------------------------------------------------------------------------
    # chest, bonus, loot for
    # - Noceros
    # - Saberfang
    "310a": ["[Legendary]Noceros Chest", "Chest", "", 5, 4, ""],
    "320a": ["[Legendary]Saberfang Chest", "Chest", "", 5, 4, ""],
    "330a": ["[Uncommon]Noceros Bonus", "Bonus", "", 2, 1, ""],
    "340a": ["[Rare]Noceros Bonus", "Bonus", "", 3, 1, ""],
    "350a": ["[Epic]Noceros Bonus", "Bonus", "", 4, 1, ""],
    "360a": ["[Legendary]Noceros Bonus", "Bonus", "", 5, 1, ""],
    "370a": ["[Uncommon]Saberfang Bonus", "Bonus", "", 2, 1, ""],
    "380a": ["[Rare]Saberfang Bonus", "Bonus", "", 3, 1, ""],
    "390a": ["[Epic]Saberfang Bonus", "Bonus", "", 4, 1, ""],
    "3a0a": ["[Legendary]Saberfang Bonus", "Bonus", "", 5, 1, ""],
    "3b0a": ["[Common]Noceros Loot", "Loot", "", 1, 0, "Noceros"],
    "3c0a": ["[Uncommon]Noceros Loot", "Loot", "", 2, 0, "Noceros"],
    "3d0a": ["[Rare]Noceros Loot", "Loot", "", 3, 0, "Noceros"],
    "3e0a": ["[Epic]Noceros Loot", "Loot", "", 4, 0, "Noceros"],
    "3f0a": ["[Legendary]Noceros Loot", "Loot", "", 5, 0, "Noceros"],
    "400a": ["[Common]Saberfang Loot", "Loot", "", 1, 0, "Saberfang"],
    "410a": ["[Uncommon]Saberfang Loot", "Loot", "", 2, 0, "Saberfang"],
    "420a": ["[Rare]Saberfang Loot", "Loot", "", 3, 0, "Saberfang"],
    "430a": ["[Epic]Saberfang Loot", "Loot", "", 4, 0, "Saberfang"],
    "440a": ["[Legendary]Saberfang Loot", "Loot", "", 5, 0, "Saberfang"],
    # -------------------------------------------------------------------------

    # "450a": ["", "", "", -1, -1, ""],
    # "460a": ["", "", "", -1, -1, ""],
    "470a": ["[Uncommon]]HeroGiftPack", "Bonus", "", 2, 1, ""],
    "480a": ["[Rare]HeroGiftPack", "Bonus", "", 3, 1, ""],
    "490a": ["[Epic]HeroGiftPack", "Bonus", "", 4, 1, ""],
    "4a0a": ["[Legendary]HeroGiftPack", "Bonus", "", 5, 1, ""],
    # "4b0a": ["", "", "", -1, -1, ""],
    # "4c0a": ["", "", "", -1, -1, ""],

    # -------------------------------------------------------------------------
    # chest, bonus, loot for
    # - Blackwing
    # - Mecha Trojan
    "4d0a": ["[Legendary]Blackwing Chest", "Chest", "", 5, 4, ""],
    "4e0a": ["[Legendary]Mecha Trojan Chest", "Chest", "", 5, 4, ""],
    "4f0a": ["[Uncommon]Blackwing Bonus", "Bonus", "", 2, 1, ""],
    "500a": ["[Rare]Blackwing Bonus", "Bonus", "", 3, 1, ""],
    "510a": ["[Epic]Blackwing Bonus", "Bonus", "", 4, 1, ""],
    "520a": ["[Legendary]Blackwing Bonus", "Bonus", "", 5, 1, ""],
    "530a": ["[Uncommon]Mecha Trojan Bonus", "Bonus", "", 2, 1, ""],
    "540a": ["[Rare]Mecha Trojan Bonus", "Bonus", "", 3, 1, ""],
    "550a": ["[Epic]Mecha Trojan Bonus", "Bonus", "", 4, 1, ""],
    "560a": ["[Legendary]Mecha Trojan Bonus", "Bonus", "", 5, 1, ""],
    "570a": ["[Common]Blackwing Loot", "Loot", "", 1, 0, "Blackwing"],
    "580a": ["[Uncommon]Blackwing Loot", "Loot", "", 2, 0, "Blackwing"],
    "590a": ["[Rare]Blackwing Loot", "Loot", "", 3, 0, "Blackwing"],
    "5a0a": ["[Epic]Blackwing Loot", "Loot", "", 4, 0, "Blackwing"],
    "5b0a": ["[Legendary]Blackwing Loot", "Loot", "", 5, 0, "Blackwing"],
    "5c0a": ["[Common]Mecha Trojan Loot", "Loot", "", 1, 0, "Mecha Trojan"],
    "5d0a": ["[Uncommon]Mecha Trojan Loot", "Loot", "", 2, 0, "Mecha Trojan"],
    "5e0a": ["[Rare]Mecha Trojan Loot", "Loot", "", 3, 0, "Mecha Trojan"],
    "5f0a": ["[Epic]Mecha Trojan Loot", "Loot", "", 4, 0, "Mecha Trojan"],
    "600a": ["[Legendary]Mecha Trojan Loot", "Loot", "", 5, 0, "Mecha Trojan"],
    # -------------------------------------------------------------------------

    # "610a": ["", "", "", -1, -1, ""],
    # "620a": ["", "", "", -1, -1, ""],
    # "630a": ["", "", "", -1, -1, ""],

    # -------------------------------------------------------------------------
    # chest, bonus, loot for Queen Bee
    "640a": ["[Legendary]Queen Bee Chest", "Chest", "", 5, 4, ""],
    "650a": ["[Uncommon]Queen Bee Bonus", "Bonus", "", 2, 1, ""],
    "660a": ["[Rare]Queen Bee Bonus", "Bonus", "", 3, 1, ""],
    "670a": ["[Epic]Queen Bee Bonus", "Bonus", "", 4, 1, ""],
    "680a": ["[Legendary]Queen Bee Bonus", "Bonus", "", 5, 1, ""],
    "690a": ["[Common]Queen Bee Loot", "Loot", "", 1, 0, "Queen Bee"],
    "6a0a": ["[Uncommon]Queen Bee Loot", "Loot", "", 2, 0, "Queen Bee"],
    "6b0a": ["[Rare]Queen Bee Loot", "Loot", "", 3, 0, "Queen Bee"],
    "6c0a": ["[Epic]Queen Bee Loot", "Loot", "", 4, 0, "Queen Bee"],
    "6d0a": ["[Legendary]Queen Bee Loot", "Loot", "", 5, 0, "Queen Bee"],
    # -------------------------------------------------------------------------

    # "6e0a": ["", "", "", -1, -1, ""],
    # "6f0a": ["", "", "", -1, -1, ""],
    # "700a": ["", "", "", -1, -1, ""],
    # "710a": ["", "", "", -1, -1, ""],
    # "720a": ["", "", "", -1, -1, ""],
    # "730a": ["", "", "", -1, -1, ""],

    # ----------------------------------------------
    # bonus, loot, chest for Bon Appeti
    "740a": ["[Uncommon]Bon Appeti Bonus", "Bonus", "", 2, 1, ""],
    "750a": ["[Rare]Bon Appeti Bonus", "Bonus", "", 3, 1, ""],
    "760a": ["[Epic]Bon Appeti Bonus", "Bonus", "", 4, 1, ""],
    "770a": ["[Legendary]Bon Appeti Bonus", "Bonus", "", 5, 1, ""],
    "780a": ["[Common]Bon Appeti Loot", "Loot", "", 1, 0, "Bon Appeti"],
    "790a": ["[Uncommon]Bon Appeti Loot", "Loot", "", 2, 0, "Bon Appeti"],
    "7a0a": ["[Rare]Bon Appeti Loot", "Loot", "", 3, 0, "Bon Appeti"],
    "7b0a": ["[Epic]Bon Appeti Loot", "Loot", "", 4, 0, "Bon Appeti"],
    "7c0a": ["[Legendary]Bon Appeti Loot", "Loot", "", 5, 0, "Bon Appeti"],
    "7d0a": ["[Legendary]Bon Appeti Chest", "Chest", "", 5, 4, ""],
    # ----------------------------------------------
    # bonus, loot, chest for Tidal Titan
    # "7ea": ["", "", "", -1, -1, ""],
    # "7f0a": ["", "", "", -1, -1, ""],
    # "800a": ["", "", "", -1, -1, ""],
    # "810a": ["", "", "", -1, -1, ""],
    "820a": ["[Common]Tidal Titan Loot", "Loot", "", 1, 0, "Tidal Titan"],
    "830a": ["[Uncommon]Tidal Titan Loot", "Loot", "", 2, 0, "Tidal Titan"],
    "840a": ["[Rare]Tidal Titan Loot", "Loot", "", 3, 0, "Tidal Titan"],
    "850a": ["[Epic]Tidal Titan Loot", "Loot", "", 4, 0, "Tidal Titan"],
    "860a": ["[Legendary]Tidal Titan Loot", "Loot", "", 5, 0, "Tidal Titan"],
    "870a": ["[Legendary]Tidal Titan Chest", "Chest", "", 5, 4, ""],
    # ----------------------------------------------

    # "880a": ["", "", "", -1, -1, ""],
    # "890a": ["", "", "", -1, -1, ""],
    # "8a0a": ["", "", "", -1, -1, ""],
    # "8b0a": ["", "", "", -1, -1, ""],
    # "8c0a": ["", "", "", -1, -1, ""],
    # "8d0a": ["", "", "", -1, -1, ""],
    # "8e0a": ["", "", "", -1, -1, ""],
    # "8f0a": ["", "", "", -1, -1, ""],
    # "900a": ["", "", "", -1, -1, ""],
    # "910a": ["", "", "", -1, -1, ""],
    # "920a": ["", "", "", -1, -1, ""],
    # "930a": ["", "", "", -1, -1, ""],
    # "940a": ["", "", "", -1, -1, ""],
    # "950a": ["", "", "", -1, -1, ""],
    # "960a": ["", "", "", -1, -1, ""],
    # "970a": ["", "", "", -1, -1, ""],
    # "980a": ["", "", "", -1, -1, ""],
    # "990a": ["", "", "", -1, -1, ""],
    # "9a0a": ["", "", "", -1, -1, ""],
    # "9b0a": ["", "", "", -1, -1, ""],
    # "9c0a": ["", "", "", -1, -1, ""],
    # "9d0a": ["", "", "", -1, -1, ""],
    # "9e0a": ["", "", "", -1, -1, ""],
    # "9f0a": ["", "", "", -1, -1, ""],
    # "a00a": ["", "", "", -1, -1, ""],
    # "a10a": ["", "", "", -1, -1, ""],
    # "a20a": ["", "", "", -1, -1, ""],
    # "a30a": ["", "", "", -1, -1, ""],
    "a40a": ["[Rare]Showdown Trove", "Event Chest", "", 3, 4, ""],
    "a70a": ["[Common]Showdown Cache", "Event Chest", "", 1, 4, ""],
    "a90a": ["[Rare]Showdown Cache", "Event Chest", "", 3, 4, ""],

    "ad0a": ["[Legendary]Fortune Chest", "Chest", "", 5, 4, ""],

    "b30a": ["[Legendary]Bouncy Chest", "Chest", "", 5, 4, ""],
    "b40a": ["Bouncy Chest", "Chest", "", 0, 4, ""],

    # ----------------------------------------------
    # Bonus, Loot, Chest for Voodoo Shaman
    # "bf0a": ["[Uncommon]Voodoo Shaman Bonus", "Bonus", "", 2, 1, ""],
    # "c00a": ["[Rare]Voodoo Shaman Bonus", "Bonus", "", 2, 1, ""],
    # "c10a": ["[Epic]Voodoo Shaman Bonus", "Bonus", "", 2, 1, ""],
    # "c20a": ["[Legendary]Voodoo Shaman Bonus", "Bonus", "", 2, 1, ""],
    "c30a": ["[Common]Voodoo Shaman Loot", "Loot", "",
             1, 0, "Voodoo Shaman"],
    "c40a": ["[Uncommon]Voodoo Shaman Loot", "Loot", "",
             2, 0, "Voodoo Shaman"],
    "c50a": ["[Rare]Voodoo Shaman Loot", "Loot", "", 3, 0, "Voodoo Shaman"],
    "c60a": ["[Epic]Voodoo Shaman Loot", "Loot", "", 4, 0, "Voodoo Shaman"],
    "c70a": ["[Legendary]Voodoo Shaman Loot", "Loot", "",
             5, 0, "Voodoo Shaman"],
    "c80a": ["[Legendary]Shaman Chest", "Chest", "", 5, 4, ""],
    # ----------------------------------------------

    "c90a": ["[Legendary]Chest of Splendor", "Chest", "", 5, -1, ""],
    # "ca0a": ["", "", "", -1, -1, ""],
    "cb0a": ["[Common]Frostwing Loot", "Loot", "", 1, 0, "Frostwing"],
    "cc0a": ["[Uncommon]Frostwing Loot", "Loot", "", 2, 0, "Frostwing"],
    "cd0a": ["[Rare]Frostwing Loot", "Loot", "", 3, 0, "Frostwing"],
    "ce0a": ["[Epic]Frostwing Loot", "Loot", "", 4, 0, "Frostwing"],
    "cf0a": ["[Legendary]Frostwing Loot", "Loot", "", 5, 0, "Frostwing"],
    # "d0a": ["", "", "", -1, -1, ""],
    # "d00a": ["", "", "", -1, -1, ""],
    # "d10a": ["", "", "", -1, -1, ""],
    # "d20a": ["", "", "", -1, -1, ""],
    # "d30a": ["", "", "", -1, -1, ""],
    # "d40a": ["", "", "", -1, -1, ""],
    # "d50a": ["", "", "", -1, -1, ""],
    # "d60a": ["", "", "", -1, -1, ""],
    # "d70a": ["", "", "", -1, -1, ""],
    # "d80a": ["", "", "", -1, -1, ""],
    # "d90a": ["", "", "", -1, -1, ""],
    # "da0a": ["", "", "", -1, -1, ""],
    # "db0a": ["", "", "", -1, -1, ""],
    # "dc0a": ["", "", "", -1, -1, ""],
    # "dd0a": ["", "", "", -1, -1, ""],
    # "de0a": ["", "", "", -1, -1, ""],
    # "df0a": ["?[Common]Snow Beast Loot", "Loot", "", 1, 0, "Snow Beast"],
    # "e00a": ["?[Uncommon]Snow Beast Loot", "Loot", "", 2, 0, "Snow Beast"],
    # "e10a": ["?[Rare]Snow Beast Loot", "Loot", "", 3, 0, "Snow Beast"],
    # "e20a": ["?[Epic]Snow Beast Loot", "Loot", "", 4, 0, "Snow Beast"],
    # "e30a": ["?[Legendary]Snow Beast Loot", "Loot", "", 5, 0, "Snow Beast"],
    # "e40a": ["", "", "", -1, -1, ""],
    # "e50a": ["", "", "", -1, -1, ""],

    # ----------------------------------------------
    # Bonus, Loot, Chest for Hardrox
    "e60a": ["[Uncommon]Hardrox Bonus", "Bonus", "", 2, 1, ""],
    "e70a": ["[Rare]Hardrox Bonus", "Bonus", "", 3, 1, ""],
    "e80a": ["[Epic]Hardrox Bonus", "Bonus", "", 4, 1, ""],
    "e90a": ["[Legendary]Hardrox Bonus", "Bonus", "", 5, 1, ""],
    "ea0a": ["[Common]Hardrox Loot", "Loot", "", 1, 0, "Hardrox"],
    "eb0a": ["[Uncommon]Hardrox Loot", "Loot", "", 2, 0, "Hardrox"],
    "ec0a": ["[Rare]Hardrox Loot", "Loot", "", 3, 0, "Hardrox"],
    "ed0a": ["[Epic]Hardrox Loot", "Loot", "", 4, 0, "Hardrox"],
    "ee0a": ["[Legendary]Hardrox Loot", "Loot", "", 5, 0, "Hardrox"],
    "ef0a": ["[Legendary]Hardrox Chest", "Chest", "", 5, 4, ""],
    # ----------------------------------------------

    # "f00a": ["", "", "", -1, -1, ""],
    # "f10a": ["", "", "", -1, -1, ""],
    # "f20a": ["", "", "", -1, -1, ""],
    # "f30a": ["", "", "", -1, -1, ""],
    # "f40a": ["", "", "", -1, -1, ""],
    "f50a": ["[Legendary]Ember Chest", "Chest", "", 5, 4, ""],
    # "f60a": ["", "", "", -1, -1, ""],
    # "f70a": ["", "", "", -1, -1, ""],
    # "f80a": ["", "", "", -1, -1, ""],
    # "f90a": ["", "", "", -1, -1, ""],
    # "fa0a": ["", "", "", -1, -1, ""],
    # "fb0a": ["", "", "", -1, -1, ""],
    # "fc0a": ["", "", "", -1, -1, ""],
    # "fd0a": ["", "", "", -1, -1, ""],
    # "fe0a": ["", "", "", -1, -1, ""],
    # "ff0a": ["", "", "", -1, -1, ""],
    # "000b": ["", "", "", -1, -1, ""],
    # "010b": ["", "", "", -1, -1, ""],
    # "020b": ["", "", "", -1, -1, ""],
    # "030b": ["", "", "", -1, -1, ""],
    # "040b": ["", "", "", -1, -1, ""],
    # "050b": ["", "", "", -1, -1, ""],
    # "060b": ["", "", "", -1, -1, ""],
    # "070b": ["", "", "", -1, -1, ""],
    # "080b": ["", "", "", -1, -1, ""],
    # "090b": ["", "", "", -1, -1, ""],
    # "0a0b": ["", "", "", -1, -1, ""],
    # "0b0b": ["", "", "", -1, -1, ""],
    # "0c0b": ["", "", "", -1, -1, ""],
    # "0d0b": ["", "", "", -1, -1, ""],
    # "0e0b": ["", "", "", -1, -1, ""],
    # "0f0b": ["", "", "", -1, -1, ""],
    # "100b": ["", "", "", -1, -1, ""],
    # "110b": ["", "", "", -1, -1, ""],
    # "120b": ["", "", "", -1, -1, ""],
    # "130b": ["", "", "", -1, -1, ""],
    "140b": ["[Legendary]Steampath Chest", "Chest", "", 5, 4, ""],
    # "150b": ["", "", "", -1, -1, ""],
    "160b": ["[Common]Summon Bonus", "Event Chest", "", 1, -1, ""],
    "170b": ["[Uncommon]Summon Bonus", "Event Chest", "", 2, -1, ""],
    "180b": ["[Rare]Summon Bonus", "Event Chest", "", 3, -1, ""],
    "190b": ["[Epic]Summon Bonus", "Event Chest", "", 4, -1, ""],
    "1a0b": ["[Legendary]Summon Bonus", "Event Chest", "", 5, 3, ""],
    "1b0b": ["[Common]Slayer Loot", "Event Chest", "", 1, 3, ""],
    "1c0b": ["[Uncommon]Slayer Loot", "Event Chest", "", 2, 3, ""],
    "1d0b": ["[Rare]Slayer Loot", "Event Chest", "", 3, 3, ""],
    "1e0b": ["[Epic]Slayer Loot", "Event Chest", "", 4, 3, ""],
    "1f0b": ["[Legendary]Slayer Loot", "Event Chest", "", 5, 3, ""],
    # "200b": ["", "", "", -1, -1, ""],
    # "210b": ["", "", "", -1, -1, ""],
    # "220b": ["", "", "", -1, -1, ""],

    # ----------------------------------------------
    # Bonus, Loot, Chest for Hootclaw
    # "230b": ["", "", "", -1, -1, ""],
    # "240b": ["", "", "", -1, -1, ""],
    # "250b": ["", "", "", -1, -1, ""],
    # "260b": ["", "", "", -1, -1, ""],
    "270b": ["[Common]Hootclaw Loot", "Loot", "", 1, 0, "Hootclaw"],
    "280b": ["[Uncommon]Hootclaw Loot", "Loot", "", 2, 0, "Hootclaw"],
    "290b": ["[Rare]Hootclaw Loot", "Loot", "", 3, 0, "Hootclaw"],
    "2a0b": ["[Epic]Hootclaw Loot", "Loot", "", 4, 0, "Hootclaw"],
    "2b0b": ["[Legendary]Hootclaw Loot", "Loot", "", 5, 0, "Hootclaw"],
    # "2c0b": ["", "", "", -1, -1, ""],

    # ----------------------------------------------
    # Bonus, Loot, Chest for Cottageroar
    "2d0b": ["[Uncommon]Cottageroar Bonus", "Bonus", "", 2, 1, ""],
    "2e0b": ["[Rare]Cottageroar Bonus", "Bonus", "", 3, 1, ""],
    "2f0b": ["[Epic]Cottageroar Bonus", "Bonus", "", 4, 1, ""],
    "300b": ["[Legendary]Cottageroar Bonus", "Bonus", "", 5, 1, ""],
    "310b": ["[Common]Cottageroar Loot", "Loot", "", 1, 0, "Cottageroar"],
    "320b": ["[Uncommon]Cottageroar Loot", "Loot", "", 2, 0, "Cottageroar"],
    "330b": ["[Rare]Cottageroar Loot", "Loot", "", 3, 0, "Cottageroar"],
    "340b": ["[Epic]Cottageroar Loot", "Loot", "", 4, 0, "Cottageroar"],
    "350b": ["[Legendary]Cottageroar Loot", "Loot", "", 5, 0, "Cottageroar"],
    # "360b": ["", "", "", -1, -1, ""],
    # ----------------------------------------------

    "370b": ["Silver Labor Chest", "Chest", "", 0, 4, ""],
    "380b": ["Gold Labor Chest", "Chest", "", 0, 4, ""],
    # "390b": ["", "", "", -1, -1, ""],
    # "3a0b": ["", "", "", -1, -1, ""],
    # "3b0b": ["", "", "", -1, -1, ""],

    # ----------------------------------------------
    # Bonus, Loot, Chest for Gawrilla
    "3c0b": ["[Uncommon]Gawrilla Bonus", "Bonus", "", 2, 1, ""],
    "3d0b": ["[Rare]Gawrilla Bonus", "Bonus", "", 3, 1, ""],
    "3e0b": ["[Epic]Gawrilla Bonus", "Bonus", "", 4, 1, ""],
    "3f0b": ["[Legendary]Gawrilla Bonus", "Bonus", "", 5, 1, ""],
    "400b": ["[Common]Gawrilla Loot", "Loot", "", 1, 0, "Gawrilla"],
    "410b": ["[Uncommon]Gawrilla Loot", "Loot", "", 2, 0, "Gawrilla"],
    "420b": ["[Rare]Gawrilla Loot", "Loot", "", 3, 0, "Gawrilla"],
    "430b": ["[Epic]Gawrilla Loot", "Loot", "", 4, 0, "Gawrilla"],
    "440b": ["[Legendary]Gawrilla Loot", "Loot", "", 5, 0, "Gawrilla"],
    "450b": ["[Legendary]Gawrilla Chest", "Chest", "", 5, 4, ""],
    # ----------------------------------------------

    # "460b": ["", "", "", -1, -1, ""],

    # ----------------------------------------------
    # Bonus, Loot, Chest for Necrosis
    "470b": ["[Uncommon]Necrosis Bonus", "Bonus", "", 2, 1, ""],
    "480b": ["[Rare]Necrosis Bonus", "Bonus", "", 3, 1, ""],
    "490b": ["[Epic]Necrosis Bonus", "Bonus", "", 4, 1, ""],
    "4a0b": ["[Legendary]Necrosis Bonus", "Bonus", "", 5, 1, ""],
    "4b0b": ["[Common]Necrosis Loot", "Loot", "", 1, 0, "Necrosis"],
    "4c0b": ["[Uncommon]Necrosis Loot", "Loot", "", 2, 0, "Necrosis"],
    "4d0b": ["[Rare]Necrosis Loot", "Loot", "", 3, 0, "Necrosis"],
    "4e0b": ["[Epic]Necrosis Loot", "Loot", "", 4, 0, "Necrosis"],
    "4f0b": ["[Legendary]Necrosis Loot", "Loot", "", 5, 0, "Necrosis"],
    "500b": ["[Legendary]Necrosis Chest", "Chest", "", 5, 4, ""],
    # ----------------------------------------------

    # "510b": ["", "", "", -1, -1, ""],
    # "520b": ["", "", "", -1, -1, ""],
    # "530b": ["", "", "", -1, -1, ""],

    # ----------------------------------------------
    # Bonus, Loot, Chest for Arctic Flipper
    "540b": ["[Uncommon]Arctic Flipper Bonus", "Bonus", "", 2, 1, ""],
    "550b": ["[Rare]Arctic Flipper Bonus", "Bonus", "", 3, 1, ""],
    "560b": ["[Epic]Arctic Flipper Bonus", "Bonus", "", 4, 1, ""],
    "570b": ["[Legendary]Arctic Flipper Bonus", "Bonus", "", 5, 1, ""],
    "580b": ["[Common]Arctic Flipper Loot", "Loot", "",
             1, 0, "Arctic Flipper"],
    "590b": ["[Uncommon]Arctic Flipper Loot", "Loot", "",
             2, 0, "Arctic Flipper"],
    "5a0b": ["[Rare]Arctic Flipper Loot", "Loot", "", 3, 0, "Arctic Flipper"],
    "5b0b": ["[Epic]Arctic Flipper Loot", "Loot", "", 4, 0, "Arctic Flipper"],
    "5c0b": ["[Legendary]Arctic Flipper Loot", "Loot", "",
             5, 0, "Arctic Flipper"],
    "5d0b": ["[Legendary]Arctic Flipper Chest", "Chest", "", 5, 4, ""],
    # ----------------------------------------------

    # "5d0b": ["", "", "", -1, -1, ""],
    # "5e0b": ["", "", "", -1, -1, ""],
    # "5f0b": ["", "", "", -1, -1, ""],

    # ----------------------------------------------
    # Bonus, Loot, Chest for Serpent Gladiator
    # "600b": ["", "", "", -1, -1, ""],
    # "610b": ["", "", "", -1, -1, ""],
    # "620b": ["", "", "", -1, -1, ""],
    # "630b": ["", "", "", -1, -1, ""],
    "640b": ["[Common]Serpent Gladiator Loot", "Loot", "",
             1, 0, "Serpent Gladiator"],
    "650b": ["[Uncommon]Serpent Gladiator Loot", "Loot", "",
             2, 0, "Serpent Gladiator"],
    "660b": ["[Rare]Serpent Gladiator Loot", "Loot", "",
             3, 0, "Serpent Gladiator"],
    "670b": ["[Epic]Serpent Gladiator Loot", "Loot", "",
             4, 0, "Serpent Gladiator"],
    "680b": ["[Legendary]Serpent Gladiator Loot", "Loot", "",
             5, 0, "Serpent Gladiator"],
    "690b": ["[Legendary]Gladiator Chest", "Chest", "", 5, 4, ""],
    # ----------------------------------------------

    "6d0b": ["Chi Jade Chest", "Event Chest", "", -1, -1, ""],
    "bd0b": ["Gallatry Chest", "Event Chest", "", -1, -1, ""],

    "7b0e": ["3,000 Anima", "Anima", "", -1, -1, ""],
    "7c0e": ["15,000 Anima", "Anima", "", -1, -1, ""],
    "7d0e": ["50,000 Anima", "Anima", "", -1, -1, ""],
    "7e0e": ["200,000 Anima", "Anima", "", -1, -1, ""],

    # ----------------------------------------------
    "a10f": ["resource tile mat", "resource tile mat", "", -1, -1, ""],
    "a20f": ["resource tile mat", "resource tile mat", "", -1, -1, ""],
    "a30f": ["resource tile mat", "resource tile mat", "", -1, -1, ""],
    "a40f": ["resource tile mat", "resource tile mat", "", -1, -1, ""],
    "a50f": ["resource tile mat", "resource tile mat", "", -1, -1, ""],
    "a60f": ["resource tile mat", "resource tile mat", "", -1, -1, ""],
    "a70f": ["resource tile mat", "resource tile mat", "", -1, -1, ""],
    "a80f": ["resource tile mat", "resource tile mat", "", -1, -1, ""],
    "a90f": ["resource tile mat", "resource tile mat", "", -1, -1, ""],
    "aa0f": ["resource tile mat", "resource tile mat", "", -1, -1, ""],
    "ab0f": ["resource tile mat", "resource tile mat", "", -1, -1, ""],
    "ac0f": ["resource tile mat", "resource tile mat", "", -1, -1, ""],
    "ad0f": ["resource tile mat", "resource tile mat", "", -1, -1, ""],
    # ----------------------------
    "ae0f": ["Frostwing Heart", "Monster Materials", "Frostwing", -1, -1, ""],
    "af0f": ["Frostwing Scale", "Monster Materials", "Frostwing", -1, -1, ""],
    "b00f": ["Frostwing Horn", "Monster Materials", "Frostwing", -1, -1, ""],
    "b10f": ["Frostwing Claw", "Monster Materials", "Frostwing", -1, -1, ""],
    "b20f": ["Iron Bolts", "Monster Materials", "Gargantua", -1, -1, ""],
    "b30f": ["Gargantuan Locks", "Monster Materials", "Gargantua", -1, -1, ""],
    "b40f": ["Gargantuan Fang", "Monster Materials", "Gargantua", -1, -1, ""],
    "b50f": ["Gargantuan Eye", "Monster Materials", "Gargantua", -1, -1, ""],
    "b60f": ["Festive Bell", "Monster Materials", "Snow Beast", -1, -1, ""],
    "b70f": ["Beast Paw", "Monster Materials", "Snow Beast", -1, -1, ""],
    "b80f": ["Beast Antlers", "Monster Materials", "Snow Beast", -1, -1, ""],
    "b90f": ["Beast Blood", "Monster Materials", "Snow Beast", -1, -1, ""],
    "ba0f": ["Gryphon Egg", "Monster Materials", "Gryphon", -1, -1, ""],
    "bb0f": ["Gryphon Quill", "Monster Materials", "Gryphon", -1, -1, ""],
    "bc0f": ["Gryphon Core", "Monster Materials", "Gryphon", -1, -1, ""],
    "bd0f": ["Jade Orb", "Monster Materials", "Jade Wyrm", -1, -1, ""],
    "be0f": ["Wyrm Scales", "Monster Materials", "Jade Wyrm", -1, -1, ""],
    "bf0f": ["Wyrm Gut", "Monster Materials", "Jade Wyrm", -1, -1, ""],
    "c00f": ["Wyrm Spine", "Monster Materials", "Jade Wyrm", -1, -1, ""],
    # "c10f": ["", "", "", -1, -1, ""],  # hunter ?
    # "c20f": ["", "", "", -1, -1, ""],  # hunter ?
    # "c30f": ["", "", "", -1, -1, ""],  # hunter ?
    # "c40f": ["", "", "", -1, -1, ""],  # hunter ?
    "c50f": ["Adamant Plate", "Materials", "", -1, -1, ""],
    # "c60f": ["", "", "", -1, -1, ""],
    "c70f": ["Velonica's Veil", "Materials", "", -1, -1, ""],
    "c80f": ["Aurichalcum", "Materials", "", -1, -1, ""],
    # "c90f": ["", "", "", -1, -1, ""],
    "ca0f": ["Terrorthorn Seed", "Monster Materials", "Terrorthorn",
             -1, -1, ""],
    "cb0f": ["Honey Jar", "Monster Materials", "Terrorthorn", -1, -1, ""],
    "cc0f": ["Terrorteeth", "Monster Materials", "Terrorthorn", -1, -1, ""],
    "cd0f": ["Terrorvine", "Monster Materials", "Terrorthorn", -1, -1, ""],
    "ce0f": ["Mega Barb", "Monster Materials", "Mega Maggot", -1, -1, ""],
    "cf0f": ["Corrosive Toxin", "Monster Materials", "Mega Maggot",
             -1, -1, ""],
    "d00f": ["Mega Egg-sac", "Monster Materials", "Mega Maggot", -1, -1, ""],
    "d10f": ["Maggot Tail", "Monster Materials", "Mega Maggot", -1, -1, ""],
    "d20f": ["Metal Scraps", "Monster Materials", "Hell Drider", -1, -1, ""],
    "d30f": ["Devil Horn", "Monster Materials", "Hell Drider", -1, -1, ""],
    "d40f": ["Mutated Brain", "Monster Materials", "Hell Drider", -1, -1, ""],
    "d50f": ["Smoldering Core", "Monster Materials", "Hell Drider",
             -1, -1, ""],
    "d60f": ["Terrorwing", "Monster Materials", "Grim Reaper", -1, -1, ""],
    "d70f": ["Corrupted Soul", "Monster Materials", "Grim Reaper", -1, -1, ""],
    "d80f": ["Ghostly Shroud", "Monster Materials", "Grim Reaper", -1, -1, ""],
    "d90f": ["Cursed Skull", "Monster Materials", "Grim Reaper", -1, -1, ""],
    "da0f": ["Blood Sucker", "Monster Materials", "Saberfang", -1, -1, ""],
    "db0f": ["Saber Tooth", "Monster Materials", "Saberfang", -1, -1, ""],
    "dc0f": ["Prehistoric Hide", "Monster Materials", "Saberfang", -1, -1, ""],
    "dd0f": ["Savage Claw", "Monster Materials", "Saberfang", -1, -1, ""],
    "de0f": ["Lightning Vial", "Monster Materials", "Noceros", -1, -1, ""],
    "df0f": ["Crackling Hide", "Monster Materials", "Noceros", -1, -1, ""],
    "e00f": ["Electric Horn", "Monster Materials", "Noceros", -1, -1, ""],
    "e10f": ["Chipped Horn", "Monster Materials", "Noceros", -1, -1, ""],
    "e20f": ["Tattooed Skin", "Monster Materials", "Gargantua", -1, -1, ""],
    "e30f": ["Maggot Teeth", "Monster Materials", "Mega Maggot", -1, -1, ""],
    "e40f": ["Wyrm Horn", "Monster Materials", "Jade Wyrm", -1, -1, ""],
    "e50f": ["Terror Pollen", "Monster Materials", "Terrorthorn", -1, -1, ""],
    "e60f": ["Glowing Eye", "Monster Materials", "Blackwing", -1, -1, ""],
    "e70f": ["Fosilized Egg", "Monster Materials", "Blackwing", -1, -1, ""],
    "e80f": ["Slimy Scale", "Monster Materials", "Blackwing", -1, -1, ""],
    "e90f": ["Crusty Horn", "Monster Materials", "Blackwing", -1, -1, ""],
    "ea0f": ["Ancient Blueprints", "Monster Materials", "Mecha Trojan",
             -1, -1, ""],
    "eb0f": ["Refined Gunpowder", "Monster Materials", "Mecha Trojan",
             -1, -1, ""],
    "ec0f": ["Rusty Horseshoe", "Monster Materials", "Mecha Trojan",
             -1, -1, ""],
    "ed0f": ["Oily Spring", "Monster Materials", "Mecha Trojan", -1, -1, ""],
    "ee0f": ["Buzzing Husk", "Monster Materials", "Queen Bee", -1, -1, ""],
    "ef0f": ["Queen Venom", "Monster Materials", "Queen Bee", -1, -1, ""],
    "f00f": ["Bee Chrysalis", "Monster Materials", "Queen Bee", -1, -1, ""],
    "f10f": ["Royal Stinger", "Monster Materials", "Queen Bee", -1, -1, ""],
    "f20f": ["AngelicPlume", "Monster Materials", "Bon Appeti", -1, -1, ""],
    "f30f": ["Holy Silk", "Monster Materials", "Bon Appeti", -1, -1, ""],
    "f40f": ["Glowing Halo", "Monster Materials", "Bon Appeti", -1, -1, ""],
    "f50f": ["Lux Bracers", "Monster Materials", "Bon Appeti", -1, -1, ""],
    "f60f": ["Ocean Breeze", "Monster Materials", "Tidal Titan", -1, -1, ""],
    "f70f": ["Glistening Pearl", "Monster Materials", "Tidal Titan",
             -1, -1, ""],
    "f80f": ["Submerged Alloy", "Monster Materials", "Tidal Titan",
             -1, -1, ""],
    "f90f": ["Drowned Echo", "Monster Materials", "Tidal Titan", -1, -1, ""],
    "fa0f": ["Stuffed Doll", "Monster Materials", "Voodoo Shaman", -1, -1, ""],
    "fb0f": ["Sacred Gem", "Monster Materials", "Voodoo Shaman", -1, -1, ""],
    "fc0f": ["Ritual Mask", "Monster Materials", "Voodoo Shaman", -1, -1, ""],
    "fd0f": ["Tribal Drum", "Monster Materials", "Voodoo Shaman", -1, -1, ""],
    "fe0f": ["Keystone", "Monster Materials", "Hardrox", -1, -1, ""],
    "ff0f": ["Golden Tooth", "Monster Materials", "Hardrox", -1, -1, ""],
    "0010": ["Aged Dragonglass", "Monster Materials", "Hardrox", -1, -1, ""],
    # "0110": ["", "", "", -1, -1, ""],
    # "0210": ["", "", "", -1, -1, ""],
    # "0310": ["", "", "", -1, -1, ""],
    # "0410": ["", "", "", -1, -1, ""],
    "0510": ["Black Oil", "Material", "", -1, -1, ""],
    "0610": ["Heat Pipe", "Material", "", -1, -1, ""],
    # "0710": ["", "", "", -1, -1, ""],
    "0810": ["Scarlet Feather", "Monster Materials", "Hootclaw", -1, -1, ""],
    "0910": ["Wild Fruit", "Monster Materials", "Hootclaw", -1, -1, ""],
    "0a10": ["Lunar Crest", "Monster Materials", "Hootclaw", -1, -1, ""],
    "0b10": ["Weeping Wood", "Monster Materials", "Hootclaw", -1, -1, ""],
    "0c10": ["Fright Fabric", "Monster Materials", "Cottageroar", -1, -1, ""],
    "0d10": ["Forbidden Tome", "Monster Materials", "Cottageroar", -1, -1, ""],
    "0e10": ["Soul Candle", "Monster Materials", "Cottageroar", -1, -1, ""],
    "0f10": ["Cursed Slab", "Monster Materials", "Cottageroar", -1, -1, ""],
    "1010": ["Gawrilla's Rage", "Monster Materials", "Gawrilla", -1, -1, ""],
    "1110": ["Brass Ring", "Monster Materials", "Gawrilla", -1, -1, ""],
    "1210": ["Mark of Fury", "Monster Materials", "Gawrilla", -1, -1, ""],
    "1310": ["Brass Spike", "Monster Materials", "Gawrilla", -1, -1, ""],
    "1410": ["Rotten Blood", "Monster Materials", "Necrosis", -1, -1, ""],
    "1510": ["Decaying Bones", "Monster Materials", "Necrosis", -1, -1, ""],
    "1610": ["Armor Fragment", "Monster Materials", "Necrosis", -1, -1, ""],
    "1710": ["Mutant Fungi", "Monster Materials", "Necrosis", -1, -1, ""],
    "1810": ["Lustrous Crystal", "Monster Materials", "Arctic Flipper",
             -1, -1, ""],
    "1910": ["Frozen Conch", "Monster Materials", "Arctic Flipper",
             -1, -1, ""],
    "1a10": ["Blubber Oil", "Monster Materials", "Arctic Flipper", -1, -1, ""],
    "1b10": ["Ambergris Crystal", "Monster Materials", "Arctic Flipper",
             -1, -1, ""],
    "1c10": ["Tough Scales", "Monster Materials", "Serpent Gladiator",
             -1, -1, ""],
    "1d10": ["Blade Tip", "Monster Materials", "Serpent Gladiator",
             -1, -1, ""],
    "1e10": ["Toxic Fang", "Monster Materials", "Serpent Gladiator",
             -1, -1, ""],
    "1f10": ["Dune Core", "Monster Materials", "Serpent Gladiator",
             -1, -1, ""],
    # -------------------
    "6910": ["Cavalry ATK Jewel", "Jewel", "", -1, -1, ""],
    "6a10": ["Infantry ATK Jewel", "Jewel", "", -1, -1, ""],
    "6b10": ["Ranged ATK Jewel", "Jewel", "", -1, -1, ""],
    # "6c10": [" ATK Jewel", "Jewel", "", -1, -1, ""],
    "6d10": ["Trap ATK Jewel", "Jewel", "", -1, -1, ""],
    "6e10": ["Cavalry DEF Jewel", "Jewel", "", -1, -1, ""],
    "6f10": ["Infantry DEF Jewel", "Jewel", "", -1, -1, ""],
    "7010": ["Ranged DEF Jewel", "Jewel", "", -1, -1, ""],
    "7110": ["Trap DEF Jewel", "Jewel", "", -1, -1, ""],
    "7210": ["Wall DEF Jewel", "Jewel", "", -1, -1, ""],
    "7310": ["Gryphon Jewel", "Jewel", "", -1, -1, ""],
    # "7410": [" Jewel", "Jewel", "", -1, -1, ""],
    "7510": ["Terror Jewel", "Monster Materials", "Terrorthorn", -1, -1, ""],
    "7610": ["Wyrm Jewel", "Monster Materials", "Jade Wyrm", -1, -1, ""],
}


OBJECT_TYPES = {
    "01": "Food",
    "02": "Stone",
    "03": "Ore",
    "04": "Timber",
    "05": "Gold",
    "06": "Gemlode",
    "08": "Darknest or Castle",
    "09": "Camp",
    "0a": "monster",
    "0b": "Base",
}

CASTLE_STATUS = {
    "02": "Burning",
    "04": "Shielded",
    "08": "Has Prisoners",
}

CASTLE_SKINS = {
    "0102": "Dark Nest",

    "0000": "Classic",
    # "0001": "",
    # "0002": "",
    "0003": "Island Paradise",
    "0004": "Arctic Base",
    "0005": "Ancient Pyramid",
    "0006": "Mystic Mansion",
    "0007": "Fantasy Palace",
    "0008": "Dragon Manor",
    "0009": "Sacred Temple",
    "000a": "Colud Villa",
    "000b": "Blazing Fortress",
    "000c": "Gilded Citadel",
    "000d": "Shadow keep",
    "000f": "Cirque du Sourire",
    "000e": "Gingerbread Chateau",
    "0010": "Samurai Shiro",
    "0011": "Forbidden Hall",
    "0012": "Pearl Coast",
    "0013": "Lion Keep",
    "0014": "Faerie Toadstool",
    "0016": "Desert Oasis",
    "0017": "Terror Lodge",
    "0018": "Owl Outpost",
    # "0019": "",
    "001a": "Treasure Galleon",
    "001b": "Childhood Playground",
    "001c": "Frozen Flight",
    "001d": "SS Wyvern",
    "001e": "Sagittarius Cloth",
    "001f": "Woodland Warden",
    "0020": "Macabre Mansion",
    # "0021": "",
    "0021": "Aurora Fantasia",
    # "0022": "",
    "0023": "Dragon Warrior",
}

MONSTER_IDS = {
    # "0100": "",
    "0200": "Frostwing",
    "0300": "Gargantua",
    "0400": "Snow Beast",
    "0500": "Jade Wyrm",
    "0600": "Gryphon",
    "0700": "Mega Maggot",
    "0800": "Terrorthorn",
    "0900": "Hell Drider",
    "0a00": "Noceros",
    # "0b00": "",
    "0c00": "Saberfang",
    "0d00": "Hardrox",
    # "0e00": "",
    "0f00": "Tidal Titan",
    "1000": "Bon Appeti",
    "1100": "Queen Bee",
    "1200": "Blackwing",
    "1300": "Mecha Trojan",
    "1400": "Serpent Gladiator",
    "1500": "Necrosis",
    # "1600": "",
    # "1700": "",
    # "1800": "",
    # "1900": "",
    # "1a00": "",
    "0b00": "Grim Reaper",
    "1b00": "Voodoo Shaman",
    "1c00": "Hootclaw",
    "1d00": "Cottageroar",
    # "1e00": "",
    # "1f00": "",
    # "2000": "",
    "2700": "Gawrilla",
    "c900": "Huey Hops"
}

EMOTICONS = [
    '0001000300',  # ニコニコ
    '0002000100',  # 泣き
    '0003000000',  # 怒り
    '0004000600',  # ハート
    '0005000200',  # ベロ
    '0006000500',  # うーん
    '0007000700',  # ハナホジ
    '0008000400',  # びっくり
    '0084000b00',
    '0085000f00',

    '0086011e00',
    '0082022b00',
    '0083034600',
    '0084034700',
    '0082034900',
    '0086023500',
    '0086034a00',
    '0088034c00',
    '0086000d00',
    '008e023d00',
    '0092024100',
    '0096024500',
]


LORD_ICON_IDS = {
    19: "Elementalist",
    27: "Femme Fatale",
    33: "doll",
    45: "hikari no tankenka",
    3008: "Arctic Flipper",
    3009: "Oath Keeper Box",
}

HERO_IDS = {
    "0200": "Black Crow",
    "0600": "Incinator",
    "0d00": "Scarlet Bolt",
    "1200": "Demon Slayer",
    "1300": "Elementalist",
    "1a00": "Dream Witch",
    "1b00": "Femme Fatale",
    "1c00": "Petite Devil",
    "2900": "Storm Fox",
    "2f00": "Cursed Hunter",
}

FORT_IDS = {
    "0000": "Base",
    "0100": "Tempest Fort",
    "0200": "Bright Fort",
    "0300": "Frozen Fort",
    "0400": "Sky Fort",
    "0500": "Lunar Fort",
    "0600": "Coment Fort",
    # ---------------------------------------
    # dragon arena
    # "": "Citadel",
    # "": "Hot Springs",
    # "": "Ancient Remains",
    # "": "Transporter",
    # "": "Outpost",
    # ---------------------------------------
    # chalice
    "1d01": "Royal Chalice",
    "1f01": "Ranged ATK Fort",
    "2401": "Coalition Army Size Fort",
    "2501": "Cavalry DEF Fort",
    "2601": "Infantry HP Fort",
}

MODES = {
    "01": "Fire Ball",
    # "02": "",
    # "03": "",
    # "04": "",

    "05": "attacking castle",
    "06": "going camp",
    "07": "going gathering",
    "08": "scouting",
    "09": "going hunting",
    "0a": "going to reinforce",
    "0b": "joining rally",
    "0c": "rallying rally",
    "0d": "sending resources",

    # "0e": "",
    "0f": "returning from camp",
    "10": "returning from gathering",
    "11": "returning from cancelled rally",
    "12": "returning from scouting",
    # "13": "",
    "14": "returning from reinforce",
    "15": "returning from sending resources",
    # "16": "",
    "17": "returning from attacking castle",
    # "18": "",
    # "19": "",
    "1a": "returning from rally",
    "1b": "returning from hunting",
}
